apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: k8s-addons
  namespace: memcached
spec:
  interval: 30s
  ref:
    branch: main
  timeout: 60s
  url: https://github.com/bmayer/k8s-addons
