apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: memcached
  namespace: memcached
spec:
  values:
    nameOverride: memcached-prod
    resources:
      requests:
        memory: 666Mi
        cpu: 666m
    service:
      type: LoadBalancer
