apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: memcached
  namespace: memcached
spec:
  values:
    nameOverride: production
    resources:
      requests:
        memory: 128Mi
        cpu: 66m
    service:
      type: LoadBalancer
