apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: memcached
  namespace: memcached
spec:
  values:
    nameOverride: production
    resources:
      requests:
        memory: 128Mi
        cpu: 67m
    service:
      type: LoadBalancer
    extraEnvVarsCM: memcached-config
    extraVolumes:
    - name: memcached-json
      configMap:
        name: memcached-json
    extraVolumeMounts:
    - name: memcached-json
      mountPath: /var
      readOnly: true
