apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: nginx
spec:
  values:
    image:
      tag: stable
    nameOverride: production
    resources:
      requests:
        memory: 128Mi
        cpu: 66m
