---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: k8s-addons
  namespace: memcached
spec:
  interval: 30s
  ref:
    branch: reorg
  timeout: 60s
  url: https://github.com/bmayer/k8s-addons
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami
  namespace: memcached
spec:
  interval: 30m
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: memcached
  namespace: memcached
spec:
  releaseName: memcached
  chart:
    spec:
      chart: memcached
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    image:
      repository: arm64v8/memcached
      tag: latest
  interval: 5m
