apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: memcached
  namespace: memcached
spec:
  releaseName: memcached
  chart:
    spec:
      chart: memcached
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    image:
      repository: arm64v8/memcached
      tag: latest
  interval: 5m
